---

- name: Ensure that PostgreSQL process or service is running
  service:
    name: postgresql
    state: started
  become: yes

- name: Add the provided roles to the PostgreSQL instance
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    port: "{{ postgresql_port }}"
    state: present
    login_user: "{{ postgresql_admin_role }}"
  become: yes
  become_user: "{{ postgresql_admin_role }}"
  with_items: "{{ postgresql_roles }}"
  when: postgresql_roles|length > 0
